# Generated by Django 4.1.5 on 2023-01-30 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Categories",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category_name", models.CharField(max_length=200)),
            ],
            options={
                "db_table": "categories",
            },
        ),
        migrations.CreateModel(
            name="Markets",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("market_name", models.CharField(max_length=200)),
                ("district", models.CharField(max_length=200)),
                ("area", models.CharField(max_length=200)),
            ],
            options={
                "db_table": "markets",
            },
        ),
        migrations.CreateModel(
            name="Items",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_name", models.CharField(max_length=200)),
                ("price", models.FloatField()),
                ("updated_at", models.DateTimeField()),
                ("updated_by", models.CharField(max_length=200)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="markets.categories",
                    ),
                ),
            ],
            options={
                "db_table": "items",
            },
        ),
        migrations.AddField(
            model_name="categories",
            name="market",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="markets.markets"
            ),
        ),
    ]
